services:
    db:
        container_name: postgres_container_HRMS
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root_password
            POSTGRES_DB: HRMS_db
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel_network

    pgadmin:
        container_name: pgadmin4_container_HRMS
        image: dpage/pgadmin4:9.0
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root_password
        ports:
            - "8082:80"
        networks:
            - laravel_network

    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: laravel_app_HRMS
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - db
        networks:
            - laravel_network

volumes:
    db_data:
networks:
    laravel_network:
